// recovery_params.h — generated by select_parameters.py (paper §3.3)
// Predictor: exact mirror of recovery_monitor.h (Alg. 1 + LPF + sync).
// N = max DTW displacement; T_on = e_max + 10% margin; T_off = 80% T_on.
// Channels: [pN pE alt phi theta psi vN vE vUp p q r] @ 50 Hz (Ts=0.02 s)
#pragma once
#define REC_WINDOW_CAP  256
#define REC_KSAFE_DEFAULT  10
static const int REC_N_DEFAULT[12] = {
    249, 249, 249, 134, 131, 249, 237, 242, 249, 180, 172, 249
};
static const float REC_TON_DEFAULT[12] = {
    1652.166424f, 1707.075649f, 269.476934f, 2.577307f, 1.544807f, 18.941066f, 584.396494f, 612.220987f, 44.036211f, 11.505689f, 13.840117f, 38.387211f
};
static const float REC_TOFF_DEFAULT[12] = {
    1321.733139f, 1365.660519f, 215.581547f, 2.061846f, 1.235846f, 15.152853f, 467.517195f, 489.776790f, 35.228969f, 9.204551f, 11.072094f, 30.709768f
};
