%% sysid_n4sid.m  --  stable subspace identification (N4SID)
% Replaces ssest (PEM) which produced an unstable predictor.
% n4sid always yields a stable predictor (eigenvalues of A-KC inside unit circle).
clear; clc;

data_path = fullfile(getenv('HOME'), 'paperImp', 'rv_recovery', 'data', 'operation_data.mat');
load(data_path);
fprintf('Loaded: %d samples @ 400 Hz\n', size(U,1));

% Downsample 400 Hz -> 50 Hz
ds = 8;
U = U(1:ds:end, :);
Y = Y(1:ds:end, :);
Ts_ds = Ts * ds;
fprintf('Downsampled to %d samples @ %.0f Hz\n', size(U,1), 1/Ts_ds);

% 12-output selection matching the state vector
y_idx_12 = [12, 13, 10, 1, 2, 3, 4, 5, 6, 11, 7, 8];  % 1-based
n_total = size(U, 1);
n_est   = round(0.7 * n_total);
U_est = U(1:n_est, :);
Y_est = Y(1:n_est, y_idx_12);

data_est = iddata(Y_est, U_est, Ts_ds);
data_est.TimeUnit = 'seconds';

fprintf('Fitting 12-state model with N4SID...\n');
opt = n4sidOptions('Display','on');
sys = n4sid(data_est, 12, opt);

fprintf('\nN4SID fit: %.2f%%\n', sys.Report.Fit.FitPercent);
A = sys.A;  B = sys.B;  C = sys.C;  D = sys.D;  K = sys.K;
Ap = A - K*C;
fprintf('A max |eigenvalue|: %.4f\n', max(abs(eig(A))));
fprintf('Predictor Ap = A-KC max |eigenvalue|: %.4f  (should be <1)\n', max(abs(eig(Ap))));

out_dir = fullfile(getenv('HOME'), 'paperImp', 'rv_recovery', 'matlab', 'models');
if ~exist(out_dir,'dir'), mkdir(out_dir); end

save(fullfile(out_dir, 'quadrotor_ArduCopter34_n4sid.mat'), ...
     'A','B','C','D','K','Ap', 'Ts_ds', 'y_idx_12');

% Overwrite model_matrices.h with stable model
fid = fopen(fullfile(out_dir, 'model_matrices.h'), 'w');
fprintf(fid, '// Auto-generated by sysid_n4sid.m (N4SID subspace identification)\n');
fprintf(fid, '// ArduCopter 3.4 quadrotor -- stable predictor form\n');
fprintf(fid, '// Predictor: x[k+1] = Ap*x[k] + (B-K*D)*u[k] + K*y[k]\n\n');
fprintf(fid, '#pragma once\n\n');
fprintf(fid, 'static const int NX = %d;\n', size(A,1));
fprintf(fid, 'static const int NU = %d;\n', size(B,2));
fprintf(fid, 'static const float TS = %.6ff;\n\n', Ts_ds);
write_matrix(fid, 'A_MAT',  A);
write_matrix(fid, 'B_MAT',  B);
write_matrix(fid, 'C_MAT',  C);
write_matrix(fid, 'D_MAT',  double(D));
write_matrix(fid, 'K_MAT',  K);
write_matrix(fid, 'AP_MAT', Ap);
fclose(fid);
fprintf('Exported: model_matrices.h\n');
fprintf('Done.\n');

function write_matrix(fid, name, M)
    M = double(M);
    [r,c] = size(M);
    fprintf(fid, 'static const float %s[%d][%d] = {\n', name, r, c);
    for i = 1:r
        fprintf(fid, '    {');
        fprintf(fid, '%.8ff, ', M(i,:));
        fprintf(fid, '},\n');
    end
    fprintf(fid, '};\n\n');
end
