%% system_identification.m
% Derives the state-space model A,B,C,D for ArduCopter 3.4 (quadrotor)
% using the System Identification Toolbox (ssest / PEM).
%
% Paper reference: Section 3.1, Eq. (1)-(2)
% State vector (Eq. 3): x = [x y z phi theta psi xdot ydot zdot p q r]'
% SI algorithm: Prediction Error Minimization (PEM)

clear; clc;
addpath(genpath(pwd));

%% 1. Load Data
data_path = fullfile(getenv('HOME'), 'paperImp', 'rv_recovery', 'data', 'operation_data.mat');
load(data_path);   % loads U, Y, Ts, u_labels, y_labels
fprintf('Loaded: %d samples, Ts=%.4f s (%.0f Hz)\n', size(U,1), Ts, 1/Ts);

% Downsample from 400 Hz to 50 Hz to keep computation tractable
ds = 8;
U = U(1:ds:end, :);
Y = Y(1:ds:end, :);
Ts = Ts * ds;
fprintf('Downsampled to %d samples @ %.0f Hz\n', size(U,1), 1/Ts);

%% 2. Split 70/30 estimation/validation
n_total = size(U, 1);
n_est   = round(0.7 * n_total);

U_est = U(1:n_est, :);          Y_est = Y(1:n_est, :);
U_val = U(n_est+1:end, :);      Y_val = Y(n_est+1:end, :);

data_est = iddata(Y_est, U_est, Ts);
data_val = iddata(Y_val, U_val, Ts);
data_est.TimeUnit = 'seconds';
data_val.TimeUnit = 'seconds';

%% 3. Per-Variable Second-Order Models
state_names = {'Roll','Pitch','Yaw', ...
               'GyrX','GyrY','GyrZ', ...
               'AccX','AccY','AccZ', ...
               'GPS_Alt','BARO_Alt', ...
               'GPS_Lat','GPS_Lng', ...
               'MagX','MagY','MagZ'};

MODEL_ORDER = 2;
models = cell(length(state_names), 1);

opt = ssestOptions;
opt.InitialState = 'estimate';
opt.SearchMethod = 'auto';
opt.Display      = 'off';

fprintf('\nFitting %d per-variable models (order %d, PEM)...\n', ...
        length(state_names), MODEL_ORDER);

for i = 1:length(state_names)
    fprintf('  [%2d/%d] %s ... ', i, length(state_names), state_names{i});
    d_i = iddata(Y_est(:,i), U_est, Ts);
    try
        sys_i = ssest(d_i, MODEL_ORDER, opt);
        models{i} = sys_i;
        fit = sys_i.Report.Fit.FitPercent;
        fprintf('fit = %.1f%%\n', fit);
    catch e
        fprintf('FAILED: %s\n', e.message);
    end
end

%% 4. Full 12-State Model
% State vector: [GPS_Lat, GPS_Lng, GPS_Alt, Roll, Pitch, Yaw, GyrX, GyrY, GyrZ, BARO_Alt, AccX, AccY]
% Column indices into Y (1-based):
%   Y cols: Roll(1) Pitch(2) Yaw(3) GyrX(4) GyrY(5) GyrZ(6) AccX(7) AccY(8) AccZ(9)
%           GPS_Alt(10) BARO_Alt(11) GPS_Lat(12) GPS_Lng(13) MagX(14) MagY(15) MagZ(16)
y_idx_12 = [12, 13, 10, 1, 2, 3, 4, 5, 6, 11, 7, 8];

fprintf('\nFitting full 12-state model...\n');
nx_full = 12;
data_12 = iddata(Y_est(:, y_idx_12), U_est, Ts);
opt_full = ssestOptions;
opt_full.InitialState = 'estimate';
opt_full.SearchMethod = 'lm';
opt_full.Display      = 'on';

sys_full = ssest(data_12, nx_full, opt_full);
fprintf('Full model fit: %.1f%%\n', sys_full.Report.Fit.FitPercent);

%% 5. Extract and Save A, B, C, D
A = sys_full.A;   % 12x12
B = sys_full.B;   % 12x4
C = sys_full.C;   % 12x12
D = sys_full.D;   % 12x4

fprintf('\nA: %dx%d  B: %dx%d  C: %dx%d  D: %dx%d\n', ...
    size(A,1),size(A,2), size(B,1),size(B,2), ...
    size(C,1),size(C,2), size(D,1),size(D,2));

out_dir = fullfile(getenv('HOME'), 'paperImp', 'rv_recovery', 'matlab', 'models');
if ~exist(out_dir, 'dir'), mkdir(out_dir); end

save(fullfile(out_dir, 'quadrotor_ArduCopter34.mat'), ...
     'A', 'B', 'C', 'D', 'Ts', 'nx_full', 'state_names', 'sys_full');

% Per-variable models
for i = 1:length(state_names)
    if ~isempty(models{i})
        fname = fullfile(out_dir, ['model_' state_names{i} '.mat']);
        m = models{i};
        save(fname, 'm');
    end
end

fprintf('\nSaved models to: %s\n', out_dir);

%% 6. Export model_matrices.h for C++ firmware
fid = fopen(fullfile(out_dir, 'model_matrices.h'), 'w');
fprintf(fid, '// Auto-generated by system_identification.m\n');
fprintf(fid, '// ArduCopter 3.4 quadrotor state-space model\n');
fprintf(fid, '// State vector: [lat,lon,alt,roll,pitch,yaw,gyrX,gyrY,gyrZ,baroAlt,accX,accY]\n\n');
fprintf(fid, '#pragma once\n\n');
fprintf(fid, 'static const int NX = %d;\n', nx_full);
fprintf(fid, 'static const int NU = %d;\n', size(B,2));
fprintf(fid, 'static const float TS = %.6ff;\n\n', Ts);
write_matrix(fid, 'A_MAT', A);
write_matrix(fid, 'B_MAT', B);
write_matrix(fid, 'C_MAT', C);
write_matrix(fid, 'D_MAT', D);
fclose(fid);
fprintf('Exported: model_matrices.h\n');

function write_matrix(fid, name, M)
    [r,c] = size(M);
    fprintf(fid, 'static const float %s[%d][%d] = {\n', name, r, c);
    for i = 1:r
        fprintf(fid, '    {');
        fprintf(fid, '%.8ff, ', M(i,:));
        fprintf(fid, '},\n');
    end
    fprintf(fid, '};\n\n');
end
